version: '3.8'

services:
  # database:
  #   image: postgres:latest
  #   ports:
  #     - 5432:5432
  #   # The `env_file` tag allows us to declare an environment file
  #   env_file:
  #     - .env # The name of your environment file (the one at the repository root)
  #   volumes: 
  #   - ./db-data/:/var/lib/postgresql/data/
  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - 80:80
  #   volumes:
  #     - ./ui/build:/usr/share/nginx/html
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  # node/express server
  backend:
    build:
      context: ./api/
    command: /app/node_modules/.bin/nodemon /app/src/index.ts
    volumes:
      - ./api/:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
  # React app
  frontend:
     build:
       context: ./ui/
       dockerfile: Dockerfile
     volumes:
       - ./ui/:/app
       - /app/node_modules
     ports:
       - "3000:3000"
     environment:
       - CHOKIDAR_USEPOLLING=true